#!/usr/bin/env node
/**
 * pipeline/scripts/generate-data.js
 *
 * Reads pipeline/data/frames.json and pipeline/data/strings.json,
 * strips pipeline-only fields (_provenance, _meta, brand),
 * reconstructs FRAME_META from each frame's _meta field,
 * and writes data.js to the project root.
 *
 * The generated data.js declares three browser globals:
 *   const RACQUETS   = [ ... ]
 *   const STRINGS    = [ ... ]
 *   const FRAME_META = { ... }
 *
 * data.js must be loaded BEFORE app.js in index.html.
 *
 * Usage:  node pipeline/scripts/generate-data.js
 *         node pipeline/scripts/generate-data.js --dry-run   (print stats only)
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const DRY_RUN  = process.argv.includes('--dry-run');
const DATA_DIR = path.join(__dirname, '..', 'data');
const OUT_FILE = path.join(__dirname, '..', '..', 'data.js');

// Pipeline-only fields that must be stripped before writing data.js.
// These fields exist only in the pipeline JSON and must never appear in
// the browser globals that app.js consumes.
const FRAME_STRIP  = new Set(['_provenance', '_meta', 'brand']);
const STRING_STRIP = new Set(['_provenance']);

// ---------------------------------------------------------------------------
// Load pipeline data
// ---------------------------------------------------------------------------

const frames  = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'frames.json')));
const strings = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'strings.json')));

// ---------------------------------------------------------------------------
// Strip pipeline-only fields and rebuild FRAME_META
// ---------------------------------------------------------------------------

const FRAME_META = {};

const RACQUETS = frames.map(frame => {
  // Capture _meta before stripping
  if (frame._meta) {
    FRAME_META[frame.id] = { ...frame._meta };
  }

  // Build clean frame object
  const clean = {};
  for (const [k, v] of Object.entries(frame)) {
    if (!FRAME_STRIP.has(k)) clean[k] = v;
  }
  return clean;
});

const STRINGS = strings.map(str => {
  const clean = {};
  for (const [k, v] of Object.entries(str)) {
    if (!STRING_STRIP.has(k)) clean[k] = v;
  }
  return clean;
});

// ---------------------------------------------------------------------------
// Sanity checks
// ---------------------------------------------------------------------------

const frameIds    = new Set(RACQUETS.map(f => f.id));
const metaIds     = new Set(Object.keys(FRAME_META));
const missingMeta = [...frameIds].filter(id => !metaIds.has(id));
const orphanMeta  = [...metaIds].filter(id => !frameIds.has(id));

if (missingMeta.length) {
  console.warn(`[generate-data:warn] ${missingMeta.length} frames have no FRAME_META entry:`, missingMeta);
}
if (orphanMeta.length) {
  console.warn(`[generate-data:warn] ${orphanMeta.length} FRAME_META keys with no frame:`, orphanMeta);
}

// Confirm no pipeline-only fields leaked into output
for (const frame of RACQUETS) {
  for (const f of FRAME_STRIP) {
    if (frame[f] !== undefined) {
      throw new Error(`Pipeline field '${f}' leaked into RACQUETS entry '${frame.id}'`);
    }
  }
}

// ---------------------------------------------------------------------------
// Serialise to JS
// ---------------------------------------------------------------------------

/**
 * Serialise a value to a compact, readable JS literal.
 * - Objects/arrays get 2-space indent at each level.
 * - Strings are double-quoted (JSON-safe).
 * - Numbers and booleans are unquoted.
 */
function serialise(val, indent) {
  return JSON.stringify(val, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : indent + line))
    .join('\n');
}

const lines = [
  '// ============================================',
  '// DATA: RACQUETS, STRINGS, FRAME_META',
  '// Generated by pipeline/scripts/generate-data.js',
  '// DO NOT EDIT — regenerate via: npm run generate-data',
  '// ============================================',
  '',
  `const RACQUETS = ${serialise(RACQUETS, '')};`,
  '',
  `const STRINGS = ${serialise(STRINGS, '')};`,
  '',
  '// ============================================',
  '// FRAME METADATA — captures what raw specs can\'t',
  '// Per-frame adjustments for technology, aero, generation improvements.',
  '// These bonuses are added on top of the physics-derived scores in calcFrameBase().',
  '//',
  '// Fields:',
  '//   aeroBonus   — aerodynamic frame design benefit → adds to power + spin',
  '//   comfortTech — vibration-dampening technology   → adds to comfort + feel',
  '//   spinTech    — textured/open-throat tech         → adds to spin',
  '//   genBonus    — generation/revision improvement   → small boost across all attrs',
  '//',
  '// Scale: 0 = none, 0.5 = minor, 1 = moderate, 1.5 = significant, 2+ = exceptional',
  '// ============================================',
  `const FRAME_META = ${serialise(FRAME_META, '')};`,
];

const output = lines.join('\n') + '\n';

// ---------------------------------------------------------------------------
// Write or dry-run
// ---------------------------------------------------------------------------

const lineCount = output.split('\n').length;
const byteCount = Buffer.byteLength(output, 'utf8');

console.log(`[generate-data] RACQUETS:   ${RACQUETS.length} frames`);
console.log(`[generate-data] STRINGS:    ${STRINGS.length} strings`);
console.log(`[generate-data] FRAME_META: ${Object.keys(FRAME_META).length} keys`);
console.log(`[generate-data] Output:     ${lineCount} lines, ${(byteCount / 1024).toFixed(1)} KB`);

if (DRY_RUN) {
  console.log('[generate-data] Dry run — not writing data.js');
} else {
  fs.writeFileSync(OUT_FILE, output, 'utf8');
  console.log(`[generate-data] Wrote ${OUT_FILE}`);
}
